development:
  adapter: postgresql
  database: notifications_spike_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: notifications_spike_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: notifications_spike_production
  pool: 5
  timeout: 5000
